version: "3"
services:
  elasticsearch:
    image: perplexedgamer/elastic-savi:latest
    ports:
      - 9200:9200
    deploy:
      placement:
        constraints:
          - node.labels.role == elascale
  kibana:
    image: perplexedgamer/kibana-savi:latest
    ports:
      - 5601:5601
    deploy:
      placement:
        constraints:
          - node.labels.role == elascale
    environment:
      - ELASTICSEARCH_URL=http://10.11.1.17:9200
#  logstash:
#    image: perplexedgamer/logstash-savi:latest
#    ports:
#      - 5044:5044
#    deploy:
#      placement:
#        constraints:
#          - node.labels.role == elascale 
#    volumes:
#      - /home/ubuntu/elk/config/logstash.yml:/usr/share/logstash/config/logstash.yml
#      - /home/ubuntu/elk/pipeline/:/usr/share/logstash/pipeline/
