version: '3'
services:
  cass:
    image: cassandra:latest
    ports:
      - "9042:9042"
      - "7000:7000"
      - "7199:7199"
    deploy:
      placement:
        constraints:
          #- node.hostname == iot-vm3
          - node.labels.loc == core
  zookeeper:
    image: wurstmeister/zookeeper
    deploy:
      restart_policy:
        condition: on-failure
        window: 120s
      placement:
        constraints:
          #- node.hostname == iot-vm1
          - node.labels.loc == edge
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    deploy:
      restart_policy:
        condition: on-failure
        window: 120s
      placement:
        constraints:
          #- node.hostname == iot-vm1
          - node.labels.loc == edge
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.12.1.42
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "stats:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

# After all the above services are up and running: Create Sensor service
# sudo docker service create --replicas 1 --name iot_agg --constraint node.hostname==iot-vm2 perplexedgamer/sensor {KAFKA_IP_OR_10.12.1.24} 2181

# Next Create the Aggregator service   
# sudo docker service create --replicas 1 --name iot_agg --constraint node.hostname==iot-vm2 perplexedgamer/aggregator {KAFKA_IP_OR_10.12.1.24} {CASS_IP_OR_10.12.1.76}
