version: '3.2'
services:
  cass:
    image: cassandra:latest
    ports:
      -  target: 9042
         published: 9042
         protocol: tcp
         mode: host   
    deploy:
      placement:
        constraints:
          - node.labels.loc == core
  zookeeper:
    image: wurstmeister/zookeeper
    deploy:
      restart_policy:
        condition: on-failure
        window: 120s
      placement:
        constraints:
          - node.labels.loc == agg-sensor 
    ports:
      -  target: 2181 
         published: 2181
         protocol: tcp
         mode: host   
    #ports:
    #  - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M
      restart_policy:
        condition: on-failure
        window: 120s
      placement:
        constraints:
          - node.labels.loc == agg-sensor
    depends_on:
      - zookeeper
    ports:
      -  target: 9092
         published: 9092
         protocol: tcp
         mode: host   
    #ports:
    #  - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.2.1.15
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "stats:1:1"
      KAFKA_ZOOKEEPER_CONNECT: 10.2.1.15:2181
  sensor:
    image: perplexedgamer/sensor:v3
    deploy:
      placement:
        constraints:
          - node.labels.loc == agg-sensor
    environment:
      KAFKA_IP: 10.2.1.15
      KAFKA_PORT: 9092
  edge:
    image: perplexedgamer/edge_processor:v6
    deploy:
      placement:
        constraints:
          - node.labels.loc == edge
      restart_policy:
        condition: on-failure
        window: 120s
    environment:
      KAFKA_IP: 10.2.1.15
      CASS_IP: 10.2.1.12
